version: "3.7"
services:
  bot:
    image: cjverity01/modmail-bot:latest
    restart: always
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
  logviewer:
    image: ghcr.io/modmail-dev/logviewer:master
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo
    ports:
      - 80:8000
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
